### ISSUE TITLE
Build Failed with an Exception

### ISSUE THREAD

**Issue by PDshant** [fossasia/phimpme-android#1528] opened 2017-12-19 13:55 UTC
Hello...I have followed your step wise procedure. But, still I got an error. Plz, Help me to resolve this error...Plz, Help me as soon as possible...

Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildCleanDebug'.
> Build command failed.
Error while executing process E:\AndroidSdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\MyApps\phimpme-android\app\src\main\jni\Android.mk NDK_APPLICATION_MK=E:\MyApps\phimpme-android\app\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-17 NDK_OUT=E:/MyApps/phimpme-android/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\MyApps\phimpme-android\app\build\intermediates\ndkBuild\debug\lib clean}
[armeabi-v7a] Clean          : IlmImf [armeabi-v7a]
make: *** Access is denied.
  .  Stop.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by sauravvishal8797** [comment] 2017-12-19 16:23
@PDshant Make sure you have installed the NDK properly, then try to build again.

**Comment by PDshant** [comment] 2017-12-20 07:52
Thanks Brother for quick reply...
I deleted NDK and again set Newly downloaded NDK...Now that error has gone. But, new errors found as below... 

E:\MyApps\phimpme-android\app\src\main\res\values\styles.xml
Error:(191, 5) error: invalid parent reference 'style/Widget.AppCompat.Button.ButtonBar.AlertDialog'.
E:\MyApps\phimpme-android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Error:(5853) invalid parent reference 'style/Widget.AppCompat.Button.ButtonBar.AlertDialog'.
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details

**Comment by PDshant** [comment] 2017-12-22 05:31
Hello bro...Thanks for quick response...I am a beginner in android
development...I deleted past NDK and again set up newly downladed NDK...Now
past issue is resolved but I got new errors which I have qouted in GitHub.
Plz help me to resolve those errors...
Thanks in advance...

**Comment by sauravvishal8797** [comment] 2017-12-22 12:03
@PDshant  Try changing the parent reference to '@style/Widget.AppCompat.Button.ButtonBar.AlertDialog.'

**Comment by sauravvishal8797** [comment] 2017-12-22 12:05
@PDshant Try changing the parent reference to "@style/Widget.AppCompat.Button.ButtonBar.AlertDialog.".

**Comment by codedsun** [comment] 2018-02-18 18:26
Kindly close the issue, if the problem is solved.

**Closed** 2018-02-21 09:48 UTC
