### ISSUE TITLE
Allowing share via multiple platforms

### ISSUE THREAD

**Issue by harsu-ag** [fossasia/phimpme-android#83] opened 2017-03-06 22:04 UTC
**Actual Behavior**
Currently, the app allows photos to be shared explicitly via Bluetooth.

**Expected Behavior**
We can extend it to a 1 click share button that allows sharing via any app that allows Image content. 

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by Abhi2424shek** [comment] 2017-03-07 04:03
Sure go on

**Comment by Subhankar29** [comment] 2017-03-08 18:57
if the issue is not resolved I would I like to work on it.

**Comment by harsu-ag** [comment] 2017-03-10 06:40
@Subhankar29 I have resolved it

**Comment by optnio00** [comment] 2017-03-16 18:27
This issue is now solved. I already solved this add also make a PR

**Comment by Abhi2424shek** [comment] 2017-04-04 10:32
Any one else interested on this?

**Comment by saurabhjn76** [comment] 2017-04-04 10:34
may I work on this?

**Comment by Abhi2424shek** [comment] 2017-04-04 10:34
@saurabhjn76 sure

**Comment by Abhi2424shek** [comment] 2017-04-07 13:32
Closed via #314

**Closed by Abhi2424shek** 2017-04-07 13:32 UTC
Labels: Feature, In Progress
