### ISSUE TITLE
Phimpme 

### ISSUE THREAD

**Issue by thisisamitkumar** [fossasia/phimpme-android#2955] opened 2019-12-30 08:40 UTC
![WhatsApp Image 2019-12-30 at 2 06 25 PM (1)](https://user-images.githubusercontent.com/38273159/71574312-395aa600-2b0e-11ea-8c29-ae30cc34da8e.jpeg)

Phimpme is not working on my phone it has crashed. I have sent feedback as well here is the crash url
https://del.dog/iferfikibe

**Comment by TBog** [comment] 2020-01-20 20:06
duplicate of #2927

**Closed** 2020-04-10 16:19 UTC
