### ISSUE TITLE
App crashes at activity showing single photo.

### ISSUE THREAD

**Issue by naman653** [fossasia/phimpme-android#2469] opened 2019-01-29 23:25 UTC
**Actual Behaviour**
While viewing the image, if we tap on a menu icon and select description, app crashes.

**Expected Behaviour**
It should show information about the current image and description dialog box should appear.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**GIF of the issue**

![phimp me_error](https://user-images.githubusercontent.com/31595908/51988418-a3b43200-24ca-11e9-9778-30c93c6fac61.gif)

**Would you like to work on the issue?**

I would love working on this issue.

**Comment by naman653** [comment] 2019-01-30 14:40
As shown in gif, it is producing the error. Maybe it depends on the device or android version you are using.
Mine is Intex cloud flash with Andriod 5.0

**Comment by yashk2000** [comment] 2019-01-30 14:51
@naman653 maybe it's a problem with your device. I am not facing this issue. Check the logcat of the app for the cause of the crash.

**Comment by naman653** [comment] 2019-01-31 13:56
LogCat of the app -->

01-31 19:24:20.275 30682-30682/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.fossasia.phimpme, PID: 30682
    java.lang.NoSuchMethodError: No virtual method getColor(ILandroid/content/res/Resources$Theme;)I in class Landroid/content/res/Resources; or its super classes (declaration of 'android.content.res.Resources' appears in /system/framework/framework.jar)
        at org.fossasia.phimpme.gallery.activities.SingleMediaActivity.onOptionsItemSelected(SingleMediaActivity.java:1475)
        at android.app.Activity.onMenuItemSelected(Activity.java:2940)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:368)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:202)
        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
        at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1188)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3231)
        at android.widget.AbsListView$3.run(AbsListView.java:4165)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by yashk2000** [comment] 2019-06-26 14:16
I have never been able to reproduce this issue. I have also tried it on several other devices but this issue never happens. Closing this hence.

**Closed by yashk2000** 2019-06-26 14:16 UTC
Labels: Bug
