### ISSUE TITLE
Single Edit Image Page for the application

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#276] opened 2017-03-31 14:17 UTC
**Actual Behaviour**

Now there are two different edit image pages. 
 - one when we edit picture from gallery page
 - other when we click picture

**Expected Behaviour**

It would be better if we have a same page as both pages have same utility.

**Screenshots of the issue**

![screenshot_20170331-194012](https://cloud.githubusercontent.com/assets/15368561/24554343/d4c3fe6a-164a-11e7-9541-23d6b031c202.png)
![screenshot_20170331-194059](https://cloud.githubusercontent.com/assets/15368561/24554342/d48f0020-164a-11e7-8d72-6a015e012e70.png)

**Would you like to work on the issue?**

yes.

**Comment by Abhi2424shek** [comment] 2017-03-31 15:05
Duplicate of #228

**Closed by Abhi2424shek** 2017-03-31 15:05 UTC
