### ISSUE TITLE
App keeps crashing.

### ISSUE THREAD

**Issue by Saif1791** [fossasia/phimpme-android#2940] opened 2019-12-12 08:40 UTC
When I install the app and try to launch it, the app opens and as soon as i go inside the app shuts down and a dialog box pops up stating that the app has stopped working.

**To Reproduce**
 Unfortunately, Phimp.me has stopped

**Expected behavior**

**Logs**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [ ..] No
- Other:

**Comment by codedsun** [comment] 2019-12-12 08:50
Duplicate of #2927

**Comment by codedsun** [comment] 2019-12-12 08:51
@iamareebjamal Close this

**Closed** 2019-12-12 10:06 UTC
