### ISSUE TITLE
Feature: we can't share images via other apps

### ISSUE THREAD

**Issue by optnio00** [fossasia/phimpme-android#143] opened 2017-03-15 18:27 UTC
**Actual Behaviour**

Please state here what is currently happening.

**Expected Behaviour**

State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.

**Comment by Abhi2424shek** [comment] 2017-03-16 02:39
Duplicate of issue #83. Pls update the issue if it isn't the duplicate.

**Closed by Abhi2424shek** 2017-03-16 02:39 UTC
