### ISSUE TITLE
App returns to home page when Screen Locked while editing image.

### ISSUE THREAD

**Issue by VIKAS9899** [fossasia/phimpme-android#2845] opened 2019-07-30 19:31 UTC
**Describe the bug**
App returns to home page when screen is locked while editing image. Sometime app crashes doing same thing.

**To Reproduce**
1. Open Any folder
2. Click on any image
3. Click on edit icon
4. Lock the Screen
5. Go to app back

**Expected behavior**
App should go back to same editing state

**Smartphone Info:**
Device : ASUS_Z01DB     
Android Version : 8.0.0

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by rahulpansari** [comment] 2019-09-04 13:59
I would like to work on this issue

**Comment by codedsun** [comment] 2019-09-07 13:59
@VIKAS9899 Not reproducible for me

**Comment by codedsun** [comment] 2019-09-09 13:30
@yashk2000 please confirm this and close if not reproducible.

**Comment by yashk2000** [comment] 2019-09-09 13:44
@codedsun it's i'm not able to reproduce this issue. 

@VIKAS9899 since it is not being reproduced on the devices of 2 separate users, I'm closing this issue.

**Comment by abishekvashok** [comment] 2019-09-15 08:05
Can't reproduce, closing this issue

**Closed by abishekvashok** 2019-09-15 08:05 UTC
Labels: Bug
