### ISSUE TITLE
State of checkbox is changing automatically in setting activity

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/phimpme-android#375] opened 2017-04-20 21:39 UTC
**Actual Behaviour**

If checkbox is unchecked, it is get checked automatically
**Expected Behaviour**

It should not happen.

**Steps to reproduce it**

1.Uncheck the checkbox (checkbox with title show local photos).
2.Now move to camera activity , click a picture and press save button.
3.Move to setting activity. You will find that checkbox is get checked automatically.

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes

**Comment by Abhi2424shek** [comment] 2017-04-21 11:25
Hi, thanks for reporting this bug, however I found that, this is due to #292 and this one seems to be a variant of #292, what do you think? @amitiwary999

**Comment by amitiwary999** [comment] 2017-04-21 11:51
@Abhi2424shek I think it is different. There may be some issues like this. I am thinking of making some changes like if user select front camera then until he/she select back camera, camera remain in front side like in gallery app or instagram app. currently it is changing on closing app. should I open new issue for this.

**Comment by Abhi2424shek** [comment] 2017-04-21 12:36
If you find bugs feel free to report them, but I think the cause of this issue is because that the setting is not getting saved, am I right?

**Comment by Abhi2424shek** [comment] 2017-04-24 08:43
Closing via #379

**Closed by Abhi2424shek** 2017-04-24 08:43 UTC
