### ISSUE TITLE
The delete text in description dialog box creates a redundancy.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1845] opened 2018-02-13 04:18 UTC
**Actual Behaviour**

When you select the option of description from the overflow menu, to enter the description of the image. There is delete option on the dialog box which does nothing.

**Expected Behaviour**

The delete option should either be no present or should delete the whole entered text at once. Also the delete text color is not according to the Accent color.

**Steps to reproduce it**

Open an image in SingleMediaActivity. Click on the overflow menu and select the description option. Now you can the dialog box and the delete text which does nothing.

**Would you like to work on the issue?**
Yes.

**Comment by sauravvishal8797** [comment] 2018-02-13 06:13
@raj10071997  The delete option does deletes the text saved and the cancel button simply aborts the operation, and also the colour of the delete button varies according to the accent colour when it is enabled i.e the delete button is enabled only if there is some text saved and is disabled otherwise. The disable button colour is also same for all the buttons. So please check again and see if the issue is still there for you.

**Comment by raj10071997** [comment] 2018-02-13 06:46
@sauravvishal8797 Yeah, you are right. Actually I got confused as what this delete option does. It works after you have added some description and then if you open description dialog again this option works. Shouldn't it be displayed only when you are visiting it again and it contains the description in it because seeing it first time makes a little confusion.

**Comment by sauravvishal8797** [comment] 2018-02-13 07:34
@raj10071997  I guess its just fine, since it is in the disabled mode at first just like the ok button.

**Comment by codedsun** [comment] 2018-02-13 19:06
@raj10071997 Please close the issue if that resolves the query.

**Comment by raj10071997** [comment] 2018-02-14 05:35
@codedsun @sauravvishal8797 I think instead of delete text, it would be better if the text displayed "Delete Description". Because seeing only delete does create a little confusion of what it does, whether it deletes all the typed text at once or it deletes the saved description ( this function can only be seen by reading the snackbar message when you open the description dialog box the second time only when there is a description already saved).

**Comment by sauravvishal8797** [comment] 2018-02-14 13:50
@raj10071997 The delete button is only enabled when there is already some saved description and it is disabled if the user starts typing it again to update the description, and when the delete button is enabled the saved text is in all select mode and therefore it is clear I guess that it is going to delete the saved text, so again I think the delete button functionality is just fine.

**Comment by raj10071997** [comment] 2018-02-14 14:29
@sauravvishal8797 I am not talking about the functionality of the delete button, the functionality is good that way. I am saying that instead of "Delete" their should be "Delete description" which appears to be a more suitable title for the functionality. Also it becomes clear that the button is going to delete the saved text, only when there is a saved text present there. Generally the apps don't have the option to delete something from the database in the dialog box, that why's it creates a little confusion about it's functionality. Having a more suitable title gives a better representation of the idea of what it does. Again the functionality is good, but having a more suitable title gives a better representation of what it does in the first place and not after saving a description and then finding out about it's functionality.

**Closed** 2018-05-28 13:56 UTC
