### ISSUE TITLE
However it doesn't work

### ISSUE THREAD

**Issue by KsgMirai** [fossasia/phimpme-android#2961] opened 2020-01-01 09:15 UTC
**Describe the bug**
I can't open this app because it is always crashing when I try opening it

**Logs**

`java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fossasia.phimpme/org.fossasia.phimpme.gallery.activities.SplashScreen}: android.view.InflateException: Binary XML file line #17 in org.fossasia.phimpme:layout/abc_screen_simple: Binary XML file line #17 in org.fossasia.phimpme:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3304)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
Caused by: android.view.InflateException: Binary XML file line #17 in org.fossasia.phimpme:layout/abc_screen_simple: Binary XML file line #17 in org.fossasia.phimpme:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
Caused by: android.view.InflateException: Binary XML file line #17 in org.fossasia.phimpme:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Field.get(java.lang.Object)' on a null object reference
	at zd.a(SourceFile:3)
	at yd.a(SourceFile:16)
	at yd.a(SourceFile:1)
	at yd$a.onCreateView(SourceFile:3)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:239)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
	at yd.inflate(SourceFile:2)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at androidx.appcompat.app.AppCompatDelegateImpl.e(SourceFile:39)
	at androidx.appcompat.app.AppCompatDelegateImpl.h(SourceFile:2)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:6)
	at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:1)
	at org.fossasia.phimpme.base.BaseActivity.onCreate(SourceFile:2)
	at org.fossasia.phimpme.base.ThemedActivity.onCreate(SourceFile:1)
	at org.fossasia.phimpme.base.SharedMediaActivity.onCreate(SourceFile:1)
	at org.fossasia.phimpme.gallery.activities.SplashScreen.onCreate(SourceFile:1)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
`

**Screenshots**

No screenshot but a crash log.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Xiaomi Mi 8|
|Android Version|10|

**Would you like to work on the issue?**

No because I can't understand what the log wants to explain......

**Comment by KsgMirai** [comment] 2020-01-01 09:18
![image](https://user-images.githubusercontent.com/53310254/71639884-b3c82900-2cba-11ea-934b-115afb57c3c5.png)
Add my screenshot

**Comment by TBog** [comment] 2020-01-20 20:05
duplicate of #2927

**Closed** 2020-04-10 16:20 UTC
