### ISSUE TITLE
Could not resolve uz.shift:colorpicker:0.5

### ISSUE THREAD

**Issue by XuJian1252878** [fossasia/phimpme-android#1502] opened 2017-11-30 01:19 UTC
**Actual Behaviour**

Could not resolve uz.shift:colorpicker:0.5 when build the project app.

**LogCat for the issue**

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve uz.shift:colorpicker:0.5.
     Required by:
         project :app
      > Could not resolve uz.shift:colorpicker:0.5.
         > Could not get resource 'http://repo1.maven.org/maven2/uz/shift/colorpicker/0.5/colorpicker-0.5.pom'.
            > Could not GET 'http://repo1.maven.org/maven2/uz/shift/colorpicker/0.5/colorpicker-0.5.pom'.
               > repo1.maven.org:80 failed to respond
      > Could not resolve uz.shift:colorpicker:0.5.
         > Could not get resource 'http://dl.bintray.com/dasar/maven/uz/shift/colorpicker/0.5/colorpicker-0.5.pom'.
            > Could not GET 'http://dl.bintray.com/dasar/maven/uz/shift/colorpicker/0.5/colorpicker-0.5.pom'.
               > dl.bintray.com:80 failed to respond
      > Could not resolve uz.shift:colorpicker:0.5.
         > Could not get resource 'http://dl.bintray.com/dasar/maven/uz/shift/colorpicker/0.5/colorpicker-0.5.pom'.
            > Could not GET 'http://dl.bintray.com/dasar/maven/uz/shift/colorpicker/0.5/colorpicker-0.5.pom'.
               > dl.bintray.com:80 failed to respond

**Comment by anantprsd5** [comment] 2017-11-30 13:37
@XuJian1252878 Follow the Development setup guide from README.md, if the build fails, try to clean and rebuild the project, it should succeed.

**Comment by XuJian1252878** [comment] 2017-12-02 00:22
@anantprsd5 
When I build the project following the Development setup guide from README.md, the log is as following:

> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve uz.shift:colorpicker:0.5.
     Required by:
         project :app
      > Could not resolve uz.shift:colorpicker:0.5.
         > Could not get resource 'http://repo1.maven.org/maven2/uz/shift/colorpicker/0.5/colorpicker-0.5.pom'.
            > Could not GET 'http://repo1.maven.org/maven2/uz/shift/colorpicker/0.5/colorpicker-0.5.pom'.
               > repo1.maven.org:80 failed to respond
      > Could not resolve uz.shift:colorpicker:0.5.
         > Could not get resource 'http://dl.bintray.com/dasar/maven/uz/shift/colorpicker/0.5/colorpicker-0.5.pom'.
            > Could not GET 'http://dl.bintray.com/dasar/maven/uz/shift/colorpicker/0.5/colorpicker-0.5.pom'.
               > dl.bintray.com:80 failed to respond
      > Could not resolve uz.shift:colorpicker:0.5.
         > Could not get resource 'http://dl.bintray.com/dasar/maven/uz/shift/colorpicker/0.5/colorpicker-0.5.pom'.
            > Could not GET 'http://dl.bintray.com/dasar/maven/uz/shift/colorpicker/0.5/colorpicker-0.5.pom'.
               > dl.bintray.com:80 failed to respond

 The log contains the line 'dl.bintray.com:80 failed to respond', is there some wrong with the repository?

**Comment by codedsun** [comment] 2018-02-18 18:23
Kindly close the issue, if the problem is solved.

**Closed** 2018-02-21 09:49 UTC
