### ISSUE TITLE
Upon changing orientation, images on the screen change

### ISSUE THREAD

**Issue by sonusourav** [fossasia/phimpme-android#2812] opened 2019-07-06 04:28 UTC
**Describe the bug**
For some images, when we change the orientation from landscape to portrait, the images on the screen change. I could not generalize for which type of images is this true at the moment, but I have found 3 such images till this time. Also, I have not observed vice-versa of this i.e. happening something similar when changing orientation from portrait to landscape.

**To Reproduce**
1. Open the image.
2. Change the orientation from landscape to portrait.

**Expected behavior**
Images on the screen should remain the same upon changing orientation.

**Gif**

![overlapping_images](https://user-images.githubusercontent.com/34706326/60751526-3bff9700-9fd4-11e9-9df2-e779f107e430.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi 4|
|Android Version| Android Nougat |

**Additional context**
I would update if I find any generalities between such images.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by VIKAS9899** [comment] 2019-07-30 18:50
image looks little scrolled.This Happens when we open Last image from the folder

**Comment by codedsun** [comment] 2019-11-03 09:27
@yashk2000 Are you able to reproduce this, I am not able to reproduce. Please close this, if not reproducible

**Comment by yashk2000** [comment] 2019-11-03 09:31
@codedsun I was also not able to reproduce the issue. 
@sonusourav for now, I'm closing the issue, if you are able to give any more inputs to this issue, please comment here.

**Closed by yashk2000** 2019-11-03 09:31 UTC
Labels: Bug
